# Generated by Django 3.2.25 on 2025-07-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('Ingreso', 'Ingreso'), ('Gasto', 'Gasto')], default='gasto', max_length=45),
            preserve_default=False,
        ),
    ]
