# Generated by Django 3.2.25 on 2025-08-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventofinanciero',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
