# Generated by Django 3.2.25 on 2025-08-11 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_categoria_descripcion'),
        ('events', '0002_alter_eventofinanciero_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventofinanciero',
            name='categorias',
        ),
        migrations.AddField(
            model_name='eventofinanciero',
            name='categoria',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='categories.categoria'),
            preserve_default=False,
        ),
    ]
